/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2022 liujuan1@allwinnertech.com
 */

#ifndef _DT_BINDINGS_CLK_SUN55IW3_DSP_CCU_H_
#define _DT_BINDINGS_CLK_SUN55IW3_DSP_CCU_H_

#define CLK_PLL_DSP_AUDIO1	0
#define CLK_PLL_DSP_AUDIO1_DIV2	1
#define CLK_PLL_DSP_AUDIO1_DIV5	2
#define CLK_PLL_DSP_AUDIO_OUT	3
#define CLK_DSP_DSP		4
#define CLK_DSP_I2S0		5
#define CLK_DSP_I2S1		6
#define CLK_DSP_I2S2		7
#define CLK_DSP_I2S3		8
#define CLK_DSP_I2S3_ASRC	9
#define CLK_BUS_DSP_I2S0	10
#define CLK_BUS_DSP_I2S1	11
#define CLK_BUS_DSP_I2S2	12
#define CLK_BUS_DSP_I2S3	13
#define CLK_DSP_SPDIF_TX	14
#define CLK_DSP_SPDIF_RX	15
#define CLK_BUS_DSP_SPDIF	16
#define CLK_DSP_DMIC		17
#define CLK_BUS_DSP_DMIC	18
#define CLK_DSP_AUDIO_CODEC_DAC	19
#define CLK_DSP_AUDIO_CODEC_ADC	20
#define CLK_BUS_DSP_AUDIO_CODEC	21
#define CLK_BUS_DSP_MSG		22
#define CLK_BUS_DSP_CFG		23
#define CLK_BUS_DSP_NPU_ACLK	24
#define CLK_BUS_DSP_NPU_HCLK	25
#define CLK_BUS_DSP_NPU		26
#define CLK_DSP_TIMER0		27
#define CLK_DSP_TIMER1		28
#define CLK_DSP_TIMER2		29
#define CLK_DSP_TIMER3		30
#define CLK_DSP_TIMER4		31
#define CLK_DSP_TIMER5		32
#define CLK_BUS_DSP_TIMER	33
#define CLK_BUS_DSP_DMA		34
#define CLK_BUS_DSP_TZMA0	35
#define CLK_BUS_DSP_TZMA1	36
#define CLK_BUS_DSP_PUBSRAM	37
#define CLK_BUS_DSP_MBUS	38
#define CLK_BUS_DSP_DMA_MBUS	39
#define CLK_DSP_RV		40
#define CLK_BUS_DSP_RV_CFG	41
#define CLK_BUS_DSP_RISCV_MSG	42
#define CLK_DSP_PWM		43
#define CLK_BUS_DSP_PWM		44
#define CLK_BUS_DSP_AHB_AUTO	45

#define CLK_DSP_NUMBER		(CLK_BUS_DSP_AHB_AUTO + 1)

#endif /* _DT_BINDINGS_CLK_SUN55IW3_DSP_CCU_H_ */
